// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: events/v1/events.proto

package eventsv1connect

import (
	v1 "OlympusGCP-Events/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/events/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventsServiceName is the fully-qualified name of the EventsService service.
	EventsServiceName = "events.v1.EventsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventsServicePublishProcedure is the fully-qualified name of the EventsService's Publish RPC.
	EventsServicePublishProcedure = "/events.v1.EventsService/Publish"
	// EventsServiceCreateTaskProcedure is the fully-qualified name of the EventsService's CreateTask
	// RPC.
	EventsServiceCreateTaskProcedure = "/events.v1.EventsService/CreateTask"
	// EventsServicePauseQueueProcedure is the fully-qualified name of the EventsService's PauseQueue
	// RPC.
	EventsServicePauseQueueProcedure = "/events.v1.EventsService/PauseQueue"
	// EventsServiceResumeQueueProcedure is the fully-qualified name of the EventsService's ResumeQueue
	// RPC.
	EventsServiceResumeQueueProcedure = "/events.v1.EventsService/ResumeQueue"
	// EventsServicePurgeQueueProcedure is the fully-qualified name of the EventsService's PurgeQueue
	// RPC.
	EventsServicePurgeQueueProcedure = "/events.v1.EventsService/PurgeQueue"
	// EventsServiceCreateJobProcedure is the fully-qualified name of the EventsService's CreateJob RPC.
	EventsServiceCreateJobProcedure = "/events.v1.EventsService/CreateJob"
)

// EventsServiceClient is a client for the events.v1.EventsService service.
type EventsServiceClient interface {
	Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error)
	// Tasks Advanced
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error)
	PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error)
	CreateJob(context.Context, *connect.Request[v1.CreateJobRequest]) (*connect.Response[v1.CreateJobResponse], error)
}

// NewEventsServiceClient constructs a client for the events.v1.EventsService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventsServiceMethods := v1.File_events_v1_events_proto.Services().ByName("EventsService").Methods()
	return &eventsServiceClient{
		publish: connect.NewClient[v1.PublishRequest, v1.PublishResponse](
			httpClient,
			baseURL+EventsServicePublishProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("Publish")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+EventsServiceCreateTaskProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		pauseQueue: connect.NewClient[v1.PauseQueueRequest, v1.PauseQueueResponse](
			httpClient,
			baseURL+EventsServicePauseQueueProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("PauseQueue")),
			connect.WithClientOptions(opts...),
		),
		resumeQueue: connect.NewClient[v1.ResumeQueueRequest, v1.ResumeQueueResponse](
			httpClient,
			baseURL+EventsServiceResumeQueueProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("ResumeQueue")),
			connect.WithClientOptions(opts...),
		),
		purgeQueue: connect.NewClient[v1.PurgeQueueRequest, v1.PurgeQueueResponse](
			httpClient,
			baseURL+EventsServicePurgeQueueProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("PurgeQueue")),
			connect.WithClientOptions(opts...),
		),
		createJob: connect.NewClient[v1.CreateJobRequest, v1.CreateJobResponse](
			httpClient,
			baseURL+EventsServiceCreateJobProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventsServiceClient implements EventsServiceClient.
type eventsServiceClient struct {
	publish     *connect.Client[v1.PublishRequest, v1.PublishResponse]
	createTask  *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	pauseQueue  *connect.Client[v1.PauseQueueRequest, v1.PauseQueueResponse]
	resumeQueue *connect.Client[v1.ResumeQueueRequest, v1.ResumeQueueResponse]
	purgeQueue  *connect.Client[v1.PurgeQueueRequest, v1.PurgeQueueResponse]
	createJob   *connect.Client[v1.CreateJobRequest, v1.CreateJobResponse]
}

// Publish calls events.v1.EventsService.Publish.
func (c *eventsServiceClient) Publish(ctx context.Context, req *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error) {
	return c.publish.CallUnary(ctx, req)
}

// CreateTask calls events.v1.EventsService.CreateTask.
func (c *eventsServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// PauseQueue calls events.v1.EventsService.PauseQueue.
func (c *eventsServiceClient) PauseQueue(ctx context.Context, req *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error) {
	return c.pauseQueue.CallUnary(ctx, req)
}

// ResumeQueue calls events.v1.EventsService.ResumeQueue.
func (c *eventsServiceClient) ResumeQueue(ctx context.Context, req *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error) {
	return c.resumeQueue.CallUnary(ctx, req)
}

// PurgeQueue calls events.v1.EventsService.PurgeQueue.
func (c *eventsServiceClient) PurgeQueue(ctx context.Context, req *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error) {
	return c.purgeQueue.CallUnary(ctx, req)
}

// CreateJob calls events.v1.EventsService.CreateJob.
func (c *eventsServiceClient) CreateJob(ctx context.Context, req *connect.Request[v1.CreateJobRequest]) (*connect.Response[v1.CreateJobResponse], error) {
	return c.createJob.CallUnary(ctx, req)
}

// EventsServiceHandler is an implementation of the events.v1.EventsService service.
type EventsServiceHandler interface {
	Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error)
	// Tasks Advanced
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error)
	PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error)
	CreateJob(context.Context, *connect.Request[v1.CreateJobRequest]) (*connect.Response[v1.CreateJobResponse], error)
}

// NewEventsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventsServiceHandler(svc EventsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventsServiceMethods := v1.File_events_v1_events_proto.Services().ByName("EventsService").Methods()
	eventsServicePublishHandler := connect.NewUnaryHandler(
		EventsServicePublishProcedure,
		svc.Publish,
		connect.WithSchema(eventsServiceMethods.ByName("Publish")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceCreateTaskHandler := connect.NewUnaryHandler(
		EventsServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(eventsServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServicePauseQueueHandler := connect.NewUnaryHandler(
		EventsServicePauseQueueProcedure,
		svc.PauseQueue,
		connect.WithSchema(eventsServiceMethods.ByName("PauseQueue")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceResumeQueueHandler := connect.NewUnaryHandler(
		EventsServiceResumeQueueProcedure,
		svc.ResumeQueue,
		connect.WithSchema(eventsServiceMethods.ByName("ResumeQueue")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServicePurgeQueueHandler := connect.NewUnaryHandler(
		EventsServicePurgeQueueProcedure,
		svc.PurgeQueue,
		connect.WithSchema(eventsServiceMethods.ByName("PurgeQueue")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceCreateJobHandler := connect.NewUnaryHandler(
		EventsServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(eventsServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/events.v1.EventsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventsServicePublishProcedure:
			eventsServicePublishHandler.ServeHTTP(w, r)
		case EventsServiceCreateTaskProcedure:
			eventsServiceCreateTaskHandler.ServeHTTP(w, r)
		case EventsServicePauseQueueProcedure:
			eventsServicePauseQueueHandler.ServeHTTP(w, r)
		case EventsServiceResumeQueueProcedure:
			eventsServiceResumeQueueHandler.ServeHTTP(w, r)
		case EventsServicePurgeQueueProcedure:
			eventsServicePurgeQueueHandler.ServeHTTP(w, r)
		case EventsServiceCreateJobProcedure:
			eventsServiceCreateJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventsServiceHandler struct{}

func (UnimplementedEventsServiceHandler) Publish(context.Context, *connect.Request[v1.PublishRequest]) (*connect.Response[v1.PublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.Publish is not implemented"))
}

func (UnimplementedEventsServiceHandler) CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.CreateTask is not implemented"))
}

func (UnimplementedEventsServiceHandler) PauseQueue(context.Context, *connect.Request[v1.PauseQueueRequest]) (*connect.Response[v1.PauseQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.PauseQueue is not implemented"))
}

func (UnimplementedEventsServiceHandler) ResumeQueue(context.Context, *connect.Request[v1.ResumeQueueRequest]) (*connect.Response[v1.ResumeQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.ResumeQueue is not implemented"))
}

func (UnimplementedEventsServiceHandler) PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.PurgeQueue is not implemented"))
}

func (UnimplementedEventsServiceHandler) CreateJob(context.Context, *connect.Request[v1.CreateJobRequest]) (*connect.Response[v1.CreateJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("events.v1.EventsService.CreateJob is not implemented"))
}
