// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/events/v1/events.proto

package eventsv1connect

import (
	v1x "OlympusGCP-Events/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/events/v1x"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventsServiceName is the fully-qualified name of the EventsService service.
	EventsServiceName = "olympus.events.v1.EventsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventsServicePublishProcedure is the fully-qualified name of the EventsService's Publish RPC.
	EventsServicePublishProcedure = "/olympus.events.v1.EventsService/Publish"
	// EventsServiceCreateTaskProcedure is the fully-qualified name of the EventsService's CreateTask
	// RPC.
	EventsServiceCreateTaskProcedure = "/olympus.events.v1.EventsService/CreateTask"
	// EventsServicePauseQueueProcedure is the fully-qualified name of the EventsService's PauseQueue
	// RPC.
	EventsServicePauseQueueProcedure = "/olympus.events.v1.EventsService/PauseQueue"
	// EventsServiceResumeQueueProcedure is the fully-qualified name of the EventsService's ResumeQueue
	// RPC.
	EventsServiceResumeQueueProcedure = "/olympus.events.v1.EventsService/ResumeQueue"
	// EventsServiceListTasksProcedure is the fully-qualified name of the EventsService's ListTasks RPC.
	EventsServiceListTasksProcedure = "/olympus.events.v1.EventsService/ListTasks"
	// EventsServiceCreateJobProcedure is the fully-qualified name of the EventsService's CreateJob RPC.
	EventsServiceCreateJobProcedure = "/olympus.events.v1.EventsService/CreateJob"
)

// EventsServiceClient is a client for the olympus.events.v1.EventsService service.
type EventsServiceClient interface {
	// Pub/Sub Intent
	Publish(context.Context, *connect.Request[v1x.PublishRequest]) (*connect.Response[v1x.PublishResponse], error)
	// Cloud Tasks Intent
	CreateTask(context.Context, *connect.Request[v1x.CreateTaskRequest]) (*connect.Response[v1x.CreateTaskResponse], error)
	PauseQueue(context.Context, *connect.Request[v1x.PauseQueueRequest]) (*connect.Response[v1x.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1x.ResumeQueueRequest]) (*connect.Response[v1x.ResumeQueueResponse], error)
	ListTasks(context.Context, *connect.Request[v1x.ListTasksRequest]) (*connect.Response[v1x.ListTasksResponse], error)
	// Scheduler Intent
	CreateJob(context.Context, *connect.Request[v1x.CreateJobRequest]) (*connect.Response[v1x.CreateJobResponse], error)
}

// NewEventsServiceClient constructs a client for the olympus.events.v1.EventsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventsServiceMethods := v1x.File_olympus_events_v1_events_proto.Services().ByName("EventsService").Methods()
	return &eventsServiceClient{
		publish: connect.NewClient[v1x.PublishRequest, v1x.PublishResponse](
			httpClient,
			baseURL+EventsServicePublishProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("Publish")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1x.CreateTaskRequest, v1x.CreateTaskResponse](
			httpClient,
			baseURL+EventsServiceCreateTaskProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		pauseQueue: connect.NewClient[v1x.PauseQueueRequest, v1x.PauseQueueResponse](
			httpClient,
			baseURL+EventsServicePauseQueueProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("PauseQueue")),
			connect.WithClientOptions(opts...),
		),
		resumeQueue: connect.NewClient[v1x.ResumeQueueRequest, v1x.ResumeQueueResponse](
			httpClient,
			baseURL+EventsServiceResumeQueueProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("ResumeQueue")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[v1x.ListTasksRequest, v1x.ListTasksResponse](
			httpClient,
			baseURL+EventsServiceListTasksProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		createJob: connect.NewClient[v1x.CreateJobRequest, v1x.CreateJobResponse](
			httpClient,
			baseURL+EventsServiceCreateJobProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("CreateJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventsServiceClient implements EventsServiceClient.
type eventsServiceClient struct {
	publish     *connect.Client[v1x.PublishRequest, v1x.PublishResponse]
	createTask  *connect.Client[v1x.CreateTaskRequest, v1x.CreateTaskResponse]
	pauseQueue  *connect.Client[v1x.PauseQueueRequest, v1x.PauseQueueResponse]
	resumeQueue *connect.Client[v1x.ResumeQueueRequest, v1x.ResumeQueueResponse]
	listTasks   *connect.Client[v1x.ListTasksRequest, v1x.ListTasksResponse]
	createJob   *connect.Client[v1x.CreateJobRequest, v1x.CreateJobResponse]
}

// Publish calls olympus.events.v1.EventsService.Publish.
func (c *eventsServiceClient) Publish(ctx context.Context, req *connect.Request[v1x.PublishRequest]) (*connect.Response[v1x.PublishResponse], error) {
	return c.publish.CallUnary(ctx, req)
}

// CreateTask calls olympus.events.v1.EventsService.CreateTask.
func (c *eventsServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1x.CreateTaskRequest]) (*connect.Response[v1x.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// PauseQueue calls olympus.events.v1.EventsService.PauseQueue.
func (c *eventsServiceClient) PauseQueue(ctx context.Context, req *connect.Request[v1x.PauseQueueRequest]) (*connect.Response[v1x.PauseQueueResponse], error) {
	return c.pauseQueue.CallUnary(ctx, req)
}

// ResumeQueue calls olympus.events.v1.EventsService.ResumeQueue.
func (c *eventsServiceClient) ResumeQueue(ctx context.Context, req *connect.Request[v1x.ResumeQueueRequest]) (*connect.Response[v1x.ResumeQueueResponse], error) {
	return c.resumeQueue.CallUnary(ctx, req)
}

// ListTasks calls olympus.events.v1.EventsService.ListTasks.
func (c *eventsServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1x.ListTasksRequest]) (*connect.Response[v1x.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// CreateJob calls olympus.events.v1.EventsService.CreateJob.
func (c *eventsServiceClient) CreateJob(ctx context.Context, req *connect.Request[v1x.CreateJobRequest]) (*connect.Response[v1x.CreateJobResponse], error) {
	return c.createJob.CallUnary(ctx, req)
}

// EventsServiceHandler is an implementation of the olympus.events.v1.EventsService service.
type EventsServiceHandler interface {
	// Pub/Sub Intent
	Publish(context.Context, *connect.Request[v1x.PublishRequest]) (*connect.Response[v1x.PublishResponse], error)
	// Cloud Tasks Intent
	CreateTask(context.Context, *connect.Request[v1x.CreateTaskRequest]) (*connect.Response[v1x.CreateTaskResponse], error)
	PauseQueue(context.Context, *connect.Request[v1x.PauseQueueRequest]) (*connect.Response[v1x.PauseQueueResponse], error)
	ResumeQueue(context.Context, *connect.Request[v1x.ResumeQueueRequest]) (*connect.Response[v1x.ResumeQueueResponse], error)
	ListTasks(context.Context, *connect.Request[v1x.ListTasksRequest]) (*connect.Response[v1x.ListTasksResponse], error)
	// Scheduler Intent
	CreateJob(context.Context, *connect.Request[v1x.CreateJobRequest]) (*connect.Response[v1x.CreateJobResponse], error)
}

// NewEventsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventsServiceHandler(svc EventsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventsServiceMethods := v1x.File_olympus_events_v1_events_proto.Services().ByName("EventsService").Methods()
	eventsServicePublishHandler := connect.NewUnaryHandler(
		EventsServicePublishProcedure,
		svc.Publish,
		connect.WithSchema(eventsServiceMethods.ByName("Publish")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceCreateTaskHandler := connect.NewUnaryHandler(
		EventsServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(eventsServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServicePauseQueueHandler := connect.NewUnaryHandler(
		EventsServicePauseQueueProcedure,
		svc.PauseQueue,
		connect.WithSchema(eventsServiceMethods.ByName("PauseQueue")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceResumeQueueHandler := connect.NewUnaryHandler(
		EventsServiceResumeQueueProcedure,
		svc.ResumeQueue,
		connect.WithSchema(eventsServiceMethods.ByName("ResumeQueue")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceListTasksHandler := connect.NewUnaryHandler(
		EventsServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(eventsServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceCreateJobHandler := connect.NewUnaryHandler(
		EventsServiceCreateJobProcedure,
		svc.CreateJob,
		connect.WithSchema(eventsServiceMethods.ByName("CreateJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.events.v1.EventsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventsServicePublishProcedure:
			eventsServicePublishHandler.ServeHTTP(w, r)
		case EventsServiceCreateTaskProcedure:
			eventsServiceCreateTaskHandler.ServeHTTP(w, r)
		case EventsServicePauseQueueProcedure:
			eventsServicePauseQueueHandler.ServeHTTP(w, r)
		case EventsServiceResumeQueueProcedure:
			eventsServiceResumeQueueHandler.ServeHTTP(w, r)
		case EventsServiceListTasksProcedure:
			eventsServiceListTasksHandler.ServeHTTP(w, r)
		case EventsServiceCreateJobProcedure:
			eventsServiceCreateJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventsServiceHandler struct{}

func (UnimplementedEventsServiceHandler) Publish(context.Context, *connect.Request[v1x.PublishRequest]) (*connect.Response[v1x.PublishResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.Publish is not implemented"))
}

func (UnimplementedEventsServiceHandler) CreateTask(context.Context, *connect.Request[v1x.CreateTaskRequest]) (*connect.Response[v1x.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.CreateTask is not implemented"))
}

func (UnimplementedEventsServiceHandler) PauseQueue(context.Context, *connect.Request[v1x.PauseQueueRequest]) (*connect.Response[v1x.PauseQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.PauseQueue is not implemented"))
}

func (UnimplementedEventsServiceHandler) ResumeQueue(context.Context, *connect.Request[v1x.ResumeQueueRequest]) (*connect.Response[v1x.ResumeQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.ResumeQueue is not implemented"))
}

func (UnimplementedEventsServiceHandler) ListTasks(context.Context, *connect.Request[v1x.ListTasksRequest]) (*connect.Response[v1x.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.ListTasks is not implemented"))
}

func (UnimplementedEventsServiceHandler) CreateJob(context.Context, *connect.Request[v1x.CreateJobRequest]) (*connect.Response[v1x.CreateJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.events.v1.EventsService.CreateJob is not implemented"))
}
